#!/bin/sh
PAGE=$1
ROOT=$2

sed "s,<head>,<head><link rel=\"stylesheet\" type=\"text/css\" href=\"http://www.gnome.org/default.css\"><link rel=\"icon\" type=\"image/png\" href=\"http://www.gnome.org/img/logo/foot-16.png\">,i;s,<body[^>]*>,<body><div id=\"body\">,i;/<\/body>/,//d" $PAGE

cat <<-FOOT
</div>

<div id="sidebar">
	<p class="section">Foundation</p>
	<ul>
		<li><b><a href="http://www.gnome.org/pressreleases.html">Press</a></b></li>
		<li><a href="$ROOT/organization.html">Organization</a></li>
		<li><a href="$ROOT/documentation.html">Documentation</a></li>
		<li><a href="$ROOT/membership.html">Membership</a></li>
		<li><a href="$ROOT/elections.html">Elections</a></li>
		<li><a href="$ROOT/directory.html">Directory</a></li>
		<li><a href="http://www.gnome.org/friends/">Fundraising</a></li>
	</ul>
	
</div>

<div id="hdr">
	<div id="logo"><a href="$ROOT/"><img src="http://www.gnome.org/img/spacer" alt="Home" /></a></div>
	<div id="banner"><img src="http://www.gnome.org/img/spacer" alt="" /></div>
	<p class="none"></p>
	<div id="hdrNav">
		<a href="http://www.gnome.org/about/">About GNOME</a> &middot;
		<a href="http://www.gnome.org/start/2.2/">Download</a> &middot;
		<!--<a href="http://www.gnome.org/contribute/"><i>Get Involved!</i></a> &middot;-->
		<a href="http://www.gnome.org/"><b>Users</b></a> &middot;
		<a href="http://developer.gnome.org/">Developers</a> &middot;
		<a href="http://foundation.gnome.org/">Foundation</a> &middot;
		<a href="mailto:webmaster@gnome.org">Contact</a>
	</div>
</div>

<div id="copyright">
Copyright &copy; 2003, <a href="http://www.gnome.org/">The GNOME Project</a>.<br />
<a href="http://validator.w3.org/check/referer">Optimised</a> for
<a href="http://www.w3.org/">standards</a>.
Hosted by <a href="http://www.redhat.com/">Red Hat</a>.
</div>

</body>

</html>
FOOT
