apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vote.gnome.org
  namespace: misc-web
spec:
  host: vote.gnome.org
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: vote-web
    weight: 100
  wildcardPolicy: None
