#!/bin/sh
PAGE=$1
ROOT=$2

sed "s,<head>,<head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" /><link rel=\"stylesheet\" type=\"text/css\" href=\"https://static.gnome.org/css/votedefault.css\" /><link rel=\"stylesheet\" type=\"text/css\" href=\"https://static.gnome.org/css/vote/foundation.css\" /><link rel=\"icon\" type=\"image/png\" href=\"https://static.gnome.org/img/logo/foot-16.png\" />,i;s,<body\([^>]*\)>,<body\1><div id=\"body\">,i;/<\/body>/,//d" $PAGE

cat <<-FOOT
</div>

<div id="hdr">
	<div id="logo"><a href="$ROOT/"><img src="https://static.gnome.org/img/spacer" alt="Home" /></a></div>
	<div id="banner"><img src="https://static.gnome.org/img/spacer" alt="" /></div>
	<p class="none"></p>
	<div id="hdrNav">
		<a href="https://www.gnome.org/about/">About GNOME</a> &middot;
		<a href="https://www.gnome.org/start/stable/">Download</a> &middot;
		<!--<a href="http://www.gnome.org/contribute/"><i>Get Involved!</i></a> &middot;-->
		<a href="https://www.gnome.org/">Users</a> &middot;
		<a href="https://help.gnome.org/devel">Developers</a> &middot;
		<a href="https://foundation.gnome.org/"><b>Foundation</b></a> &middot;
		<a href="https://www.gnome.org/contact/">Contact</a>
	</div>
</div>
</body>

</html>
FOOT
